### ISSUE TITLE
This repo hosts obsolete content

### ISSUE THREAD

**Issue by GaurangTandon** [A-J-C/Codecademy-Redesign-NEW-Post-Groups-#3]
Here is the latest zip file (7.0.2; i downloaded from the web store)
[bladgjamjaiaffkojoadgeelkgfgkdkp.zip](https://github.com/A-J-C/Codecademy-Redesign-NEW-Post-Groups-/files/67762/bladgjamjaiaffkojoadgeelkgfgkdkp.zip)
Submitting pull requests for each file manually was boring. So, I send you the zipped files so that you can put those files in this repo and then I can send you the pull request for the new feature that i had made.

Also, don't you think this repo's name is little too long and boring, why not simply name it as "Codecademy Redesigned"?

**Comment by A-J-C** [comment]
Thank you I'll update it :) And i dont really use this repo so I'll leave the name as it is.
