### ISSUE TITLE
The files for the new extension

### ISSUE THREAD

**Issue by GaurangTandon** [A-J-C/Codecademy-Redesign-NEW-Post-Groups-#5]
Here are the three files (manifest, image, and content script) in a zip file - 
[files.zip](https://github.com/A-J-C/Codecademy-Redesign/files/69267/files.zip)

Now just integrate them with the existing ones and push an update for everybody to enjoy! :)

**Comment by A-J-C** [comment]
Thanks Gaurang :) You missed a bit of my link off though. I added a bit on so for the "new courses" it went down to that specific section so I'll just add that little bit back in then upload everything :)

**Comment by GaurangTandon** [comment]
@A-J-C I had tried your link originally only. But, it still took me to my homepage (idk why) :/ Anyway, it might be because I am yet to work on any of those angular, git, java units so it's good you added it back :)
